version: '3.8'

services:
  api:
    image: us-east1-docker.pkg.dev/bunk-app-cloud-484307/api/main:142925ffc92fcf1d9b96b39ee75d98f1ada4ffb5
    ports:
      - "5000:5000"
    env_file:
      - .env

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  chat:
    image: us-east1-docker.pkg.dev/bunk-app-cloud-484307/chat/main:142925ffc92fcf1d9b96b39ee75d98f1ada4ffb5
    ports:
      - "5443:5443"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "bash", "-c", "[[ -e /db-initialized ]]"]
      interval: 30s
      timeout: 10s
      retries: 3

  cron:
    image: us-east1-docker.pkg.dev/bunk-app-cloud-484307/cron/main:142925ffc92fcf1d9b96b39ee75d98f1ada4ffb5
    ports:
      - "8082:8080"
    env_file:
      - .env

networks:
  default:
    driver: bridge

